/**
 *              Copyright (c) 2025 Visa, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 **/
const { readdirSync, statSync, readFileSync, writeFileSync } = require('fs');
const path = require('path');
const mkdirp = require('mkdirp');
const changeCase = require('change-case');

const { getDirs } = require('../../../../bin/fsio.cjs');

const DESTINATION = 'src/components';

const createExports = (source = path.resolve(DESTINATION)) => {
  const directories = getDirs(source); 
  const exports = directories.map(dir => {
    return `@forward './${dir}';`;
  })

  writeFileSync(
    path.resolve(`${DESTINATION}/_index.scss`), 
    [
      '/* This file is autogenerated */\n',
      exports.join('\n'),
      ''
    ].join('\n')
  );

}; 

module.exports = createExports;
