options:
  formatter: stylish
files:
  include: 'scss/**/*.scss'
rules:
  # Extends
  extends-before-mixins: 1
  extends-before-declarations: 1
  placeholder-in-extend: 0
  # Mixins
  mixins-before-declarations: 2
  # Line Spacing
  one-declaration-per-line: 1
  empty-line-between-blocks: 0
  single-line-per-selector: 1
  # Disallows
  no-attribute-selectors: 0
  no-color-hex: 0
  no-color-keywords: 1
  no-color-literals: 2
  no-combinators: 0
  no-css-comments: 0
  no-debug: 1
  no-disallowed-properties: 0
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-extends: 0
  no-ids: 1
  no-important: 0
  no-invalid-hex: 1
  no-mergeable-selectors: 1
  no-misspelled-properties: 1
  no-qualifying-elements: 0
  no-trailing-whitespace: 0
  no-trailing-zero: 1
  no-transition-all: 0
  no-universal-selectors: 0
  no-url-domains: 1
  no-url-protocols: 1
  no-vendor-prefixes: 0
  no-warn: 1
  property-units: 0
  # Nesting
  declarations-before-nesting: 1
  force-attribute-nesting: 1
  force-element-nesting: 1
  force-pseudo-nesting: 1
  # Name Formats
  class-name-format:
    - 1
    - convention: hyphenatedbem
  function-name-format: 1
  id-name-format: 0
  mixin-name-format: 1
  placeholder-name-format: 1
  variable-name-format: 2
  # Style Guide
  attribute-quotes: 1
  bem-depth: 0
  border-zero: 1
  brace-style: 2
  clean-import-paths: 1
  empty-args: 1
  hex-length: 0
  hex-notation: 1
  indentation: 2
  leading-zero: 2
  max-line-length: 0
  max-file-line-count: 0
  nesting-depth: 0
  property-sort-order: 2
  pseudo-element: 2
  quotes: 2
  shorthand-values: 0
  url-quotes: 1
  variable-for-property: 1
  zero-unit: 0
  # Inner Spacing
  space-after-comma: 2
  space-before-colon: 2
  space-after-colon: 0
  space-before-brace: 2
  space-before-bang: 2
  space-after-bang: 2
  space-between-parens: 2
  space-around-operator: 2
  # Final Items
  trailing-semicolon: 2
  final-newline: 0